apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
spec:
  containers:
    - name: eks-container
      image: redis:alpine
      volumeMounts:
        - mountPath: "/data"
          name: redis-volume
  volumes:
    - name: redis-volume
      persistentVolumeClaim:
        claimName: ebs-claim
