apiVersion: v1
kind: Pod
metadata:
  name: webserver
spec:
  containers:
    - name: eks-container
      image: 
      volumeMounts:
        - mountPath: ""
          name: pv-volume
  volumes:
    - name: pv-volume
      persistentVolumeClaim:
        claimName: ebs-claim
